language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
    - mqtt

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/thermorasp-webui
  target-branch: mqtt-dist
  keep-history: true
  on:
    branch: mqtt
